# Generated by Django 5.2.15 on 2026-07-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidang', models.CharField(help_text='Contoh: OSN IPA, Debat Bahasa Inggris', max_length=100)),
                ('kategori', models.CharField(choices=[('akademik', 'Akademik'), ('non_akademik', 'Non-Akademik'), ('olahraga', 'Olahraga'), ('seni', 'Seni')], default='akademik', max_length=20)),
                ('jumlah_prestasi', models.PositiveIntegerField(default=0, help_text='Jumlah total penghargaan diraih')),
                ('tingkat_tertinggi', models.CharField(blank=True, help_text='Contoh: Juara 1 Tingkat Provinsi', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Nama icon (opsional), contoh: trophy, medal, book', max_length=50)),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Prestasi',
                'verbose_name_plural': 'Prestasi',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=120)),
                ('subjudul', models.CharField(blank=True, max_length=255)),
                ('gambar', models.ImageField(upload_to='carousel/')),
                ('teks_tombol', models.CharField(default='Selengkapnya', max_length=50)),
                ('link_tombol', models.CharField(blank=True, default='#', max_length=255)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Slide Carousel',
                'verbose_name_plural': 'Slide Carousel',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('kategori', models.CharField(choices=[('pembelajaran', 'Kegiatan Pembelajaran'), ('event', 'Event / Tamu Spesial'), ('ekstrakurikuler', 'Ekstrakurikuler'), ('lainnya', 'Lainnya')], default='pembelajaran', max_length=20)),
                ('gambar', models.ImageField(upload_to='galeri/')),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('tampilkan_di_beranda', models.BooleanField(default=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Foto Dokumentasi',
                'verbose_name_plural': 'Foto Dokumentasi',
                'ordering': ['urutan', '-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='OverviewStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('kelas', 'Jumlah Kelas per Tingkat'), ('guru', 'Jumlah Guru'), ('gedung', 'Jumlah Gedung'), ('ekstrakurikuler', 'Jumlah Ekstrakurikuler'), ('lainnya', 'Lainnya')], max_length=20)),
                ('label', models.CharField(help_text='Contoh: Kelas 1, Kelas 2, Guru Tetap', max_length=100)),
                ('nilai', models.PositiveIntegerField(default=0)),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistik Overview',
                'verbose_name_plural': 'Statistik Overview',
                'ordering': ['tipe', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='mitra/')),
                ('website', models.URLField(blank=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mitra Kerja Sama',
                'verbose_name_plural': 'Mitra Kerja Sama',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(default='SDN Harapan Bangsa', max_length=150)),
                ('tagline', models.CharField(blank=True, help_text='Kalimat pendek di bawah nama sekolah', max_length=200)),
                ('deskripsi', models.TextField(help_text="Paragraf 'Tentang Sekolah'")),
                ('tahun_berdiri', models.PositiveIntegerField(default=1990)),
                ('alamat', models.CharField(blank=True, max_length=255)),
                ('video_url', models.URLField(blank=True, help_text='Link embed YouTube, contoh: https://www.youtube.com/embed/xxxxxxxx')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'verbose_name': 'Profil Sekolah',
                'verbose_name_plural': 'Profil Sekolah',
            },
        ),
    ]
