# Generated by Django 5.2.15 on 2026-07-15 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_siswa_email_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutiGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('alasan', models.TextField()),
                ('status', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Menunggu', max_length=20)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_cuti', to='accounts.guru')),
            ],
            options={
                'verbose_name': 'Cuti Guru/Staf',
                'verbose_name_plural': 'Cuti Guru/Staf',
            },
        ),
        migrations.CreateModel(
            name='PengajuanAnggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('file_proposal', models.FileField(blank=True, null=True, upload_to='proposal_anggaran/')),
                ('status', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Menunggu', max_length=20)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('pengaju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_anggaran', to='accounts.guru')),
            ],
            options={
                'verbose_name': 'Pengajuan Anggaran',
                'verbose_name_plural': 'Pengajuan Anggaran',
            },
        ),
    ]
