# Generated by Django 5.2.15 on 2026-07-15 03:31

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akademik', '0005_pendaftarppdb_raport_is_signed_by_kepsek_and_more'),
        ('guru_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanKelulusan',
            fields=[
            ],
            options={
                'verbose_name': 'Laporan Kelulusan',
                'verbose_name_plural': 'Laporan Kelulusan',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('akademik.raport',),
        ),
        migrations.CreateModel(
            name='LaporanMutasi',
            fields=[
            ],
            options={
                'verbose_name': 'Laporan Mutasi',
                'verbose_name_plural': 'Laporan Mutasi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('akademik.mutasisiswa',),
        ),
        migrations.CreateModel(
            name='LaporanPPDB',
            fields=[
            ],
            options={
                'verbose_name': 'Laporan PPDB',
                'verbose_name_plural': 'Laporan PPDB',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('akademik.pendaftarppdb',),
        ),
        migrations.CreateModel(
            name='PersetujuanAnggaran',
            fields=[
            ],
            options={
                'verbose_name': 'Persetujuan Anggaran',
                'verbose_name_plural': 'Persetujuan Anggaran',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('guru_panel.pengajuananggaran',),
        ),
        migrations.CreateModel(
            name='PersetujuanCuti',
            fields=[
            ],
            options={
                'verbose_name': 'Persetujuan Cuti',
                'verbose_name_plural': 'Persetujuan Cuti',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('guru_panel.cutiguru',),
        ),
        migrations.CreateModel(
            name='TandaTanganRaport',
            fields=[
            ],
            options={
                'verbose_name': 'Tanda Tangan Raport',
                'verbose_name_plural': 'Tanda Tangan Raport',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('akademik.raport',),
        ),
    ]
