# Generated by Django 5.2.15 on 2026-07-09 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIP')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('posisi', models.CharField(choices=[('Kepala Sekolah', 'Kepala Sekolah'), ('Guru Kelas', 'Guru Kelas'), ('Guru Mata Pelajaran', 'Guru Mata Pelajaran'), ('Staf', 'Staf')], default='Guru Kelas', max_length=50)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10)),
                ('no_telepon', models.CharField(blank=True, max_length=15, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_guru/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_guru', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guru',
                'verbose_name_plural': 'Guru',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.CharField(max_length=50, unique=True, verbose_name='NISN')),
                ('nis', models.CharField(max_length=50, unique=True, verbose_name='NIS')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('nama_ayah', models.CharField(blank=True, max_length=150, null=True)),
                ('nama_ibu', models.CharField(blank=True, max_length=150, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_siswa/')),
                ('user', models.OneToOneField(help_text='Akun untuk siswa (opsional)', on_delete=django.db.models.deletion.CASCADE, related_name='profil_siswa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Siswa',
                'verbose_name_plural': 'Siswa',
            },
        ),
    ]
