# Generated by Django 5.2.15 on 2026-07-09 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mapel', models.CharField(max_length=20, unique=True)),
                ('nama_mapel', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mata Pelajaran',
                'verbose_name_plural': 'Mata Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.CharField(choices=[('1', 'Kelas 1'), ('2', 'Kelas 2'), ('3', 'Kelas 3'), ('4', 'Kelas 4'), ('5', 'Kelas 5'), ('6', 'Kelas 6')], max_length=2)),
                ('nama_kelas', models.CharField(help_text='Contoh: 1A, 1B', max_length=10)),
                ('wali_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_diwali', to='accounts.guru')),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
            },
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_nilai', models.CharField(choices=[('Tugas', 'Tugas'), ('UH', 'Ulangan Harian'), ('UTS', 'Ujian Tengah Semester'), ('UAS', 'Ujian Akhir Semester')], max_length=20)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.kelas')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.matapelajaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='accounts.siswa')),
            ],
            options={
                'verbose_name': 'Nilai',
                'verbose_name_plural': 'Nilai',
            },
        ),
        migrations.CreateModel(
            name='SiswaKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.siswa')),
            ],
            options={
                'verbose_name': 'Siswa Kelas',
                'verbose_name_plural': 'Siswa Kelas',
                'unique_together': {('siswa', 'kelas')},
            },
        ),
        migrations.AddField(
            model_name='kelas',
            name='siswa',
            field=models.ManyToManyField(related_name='kelas_siswa', through='akademik.SiswaKelas', to='accounts.siswa'),
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: 2026/2027', max_length=20)),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10)),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Tahun Ajaran',
                'verbose_name_plural': 'Tahun Ajaran',
                'unique_together': {('nama', 'semester')},
            },
        ),
        migrations.AddField(
            model_name='kelas',
            name='tahun_ajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas', to='akademik.tahunajaran'),
        ),
        migrations.CreateModel(
            name='Raport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan_wali_kelas', models.TextField(blank=True, null=True)),
                ('izin', models.PositiveIntegerField(default=0)),
                ('sakit', models.PositiveIntegerField(default=0)),
                ('alpa', models.PositiveIntegerField(default=0)),
                ('status_naik_kelas', models.BooleanField(default=True, help_text='Centang jika naik kelas / lulus')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raport', to='accounts.siswa')),
            ],
            options={
                'verbose_name': 'Raport',
                'verbose_name_plural': 'Raport',
                'unique_together': {('siswa', 'kelas')},
            },
        ),
    ]
