# Generated by Django 5.2.15 on 2026-07-09 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('akademik', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='raport',
            name='rata_rata',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rata-rata nilai keseluruhan', max_digits=5),
        ),
        migrations.AddField(
            model_name='raport',
            name='semester',
            field=models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], default='Ganjil', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='raport',
            unique_together={('siswa', 'kelas', 'semester')},
        ),
        migrations.CreateModel(
            name='DetailRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_akhir', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.matapelajaran')),
                ('raport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_nilai', to='akademik.raport')),
            ],
            options={
                'verbose_name': 'Detail Nilai Raport',
                'verbose_name_plural': 'Detail Nilai Raport',
                'unique_together': {('raport', 'mata_pelajaran')},
            },
        ),
    ]
