# Generated by Django 5.2.15 on 2026-07-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0002_alter_raport_unique_together_raport_rata_rata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='jenis_nilai',
            field=models.CharField(choices=[('Tugas', 'Tugas'), ('Ulangan Harian 1', 'Ulangan Harian 1'), ('Ulangan Harian 2', 'Ulangan Harian 2'), ('Ulangan Harian 3', 'Ulangan Harian 3'), ('Ulangan Harian 4', 'Ulangan Harian 4'), ('UTS', 'UTS'), ('UAS', 'UAS')], max_length=20),
        ),
    ]
