# Generated by Django 5.2.15 on 2026-07-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('akademik', '0003_alter_nilai_jenis_nilai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matapelajaran',
            name='deskripsi',
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='guru_pengampu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.guru'),
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='tingkat_minimal',
            field=models.IntegerField(default=1, help_text='Tingkat kelas minimal untuk mapel ini (misal: 1 untuk kelas 1-6, 2 untuk kelas 2-6)'),
        ),
    ]
