# Generated by Django 5.2.15 on 2026-07-15 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_siswa_email_otpverification'),
        ('akademik', '0004_remove_matapelajaran_deskripsi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendaftarPPDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('asal_sekolah', models.CharField(blank=True, max_length=150, null=True)),
                ('tanggal_daftar', models.DateField(auto_now_add=True)),
                ('status_diterima', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], default='Menunggu', max_length=20)),
            ],
            options={
                'verbose_name': 'Pendaftar PPDB',
                'verbose_name_plural': 'Pendaftar PPDB',
            },
        ),
        migrations.AddField(
            model_name='raport',
            name='is_signed_by_kepsek',
            field=models.BooleanField(default=False, help_text='Ditandatangani digital oleh Kepala Sekolah'),
        ),
        migrations.AddField(
            model_name='raport',
            name='signature_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MutasiSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_mutasi', models.CharField(choices=[('Masuk', 'Masuk'), ('Keluar', 'Keluar')], max_length=10)),
                ('tanggal', models.DateField()),
                ('alasan', models.TextField()),
                ('keterangan_sekolah', models.CharField(help_text='Sekolah Asal (jika masuk) atau Sekolah Tujuan (jika keluar)', max_length=150)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutasi', to='accounts.siswa')),
            ],
            options={
                'verbose_name': 'Mutasi Siswa',
                'verbose_name_plural': 'Mutasi Siswa',
            },
        ),
    ]
