# Generated by Django 5.2.15 on 2026-07-25 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0005_pendaftarppdb_raport_is_signed_by_kepsek_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu')], max_length=10)),
                ('jam', models.CharField(help_text='Contoh: 07:00 - 08:30', max_length=50)),
                ('id_zoom', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Zoom')),
                ('passcode', models.CharField(blank=True, max_length=50, null=True)),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='Link URL')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='akademik.kelas')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='akademik.matapelajaran')),
            ],
            options={
                'verbose_name': 'Jadwal Pelajaran',
                'verbose_name_plural': 'Jadwal Pelajaran',
                'ordering': ['hari', 'jam'],
            },
        ),
    ]
