# Generated by Django 5.2.15 on 2026-07-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0006_jadwal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jadwal',
            options={'ordering': ['hari', 'jam_ke', 'jam'], 'verbose_name': 'Jadwal Pelajaran', 'verbose_name_plural': 'Jadwal Pelajaran'},
        ),
        migrations.AddField(
            model_name='jadwal',
            name='jam_ke',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], default='I', max_length=5),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='hari',
            field=models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Ahad', 'Ahad')], max_length=10),
        ),
    ]
